// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/department_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "OrgAPI/internal/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDepartmentRepository is a mock of DepartmentRepository interface.
type MockDepartmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentRepositoryMockRecorder
}

// MockDepartmentRepositoryMockRecorder is the mock recorder for MockDepartmentRepository.
type MockDepartmentRepositoryMockRecorder struct {
	mock *MockDepartmentRepository
}

// NewMockDepartmentRepository creates a new mock instance.
func NewMockDepartmentRepository(ctrl *gomock.Controller) *MockDepartmentRepository {
	mock := &MockDepartmentRepository{ctrl: ctrl}
	mock.recorder = &MockDepartmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartmentRepository) EXPECT() *MockDepartmentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDepartmentRepository) Create(ctx context.Context, department *models.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, department)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDepartmentRepositoryMockRecorder) Create(ctx, department interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDepartmentRepository)(nil).Create), ctx, department)
}

// Delete mocks base method.
func (m *MockDepartmentRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDepartmentRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDepartmentRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockDepartmentRepository) GetByID(ctx context.Context, id int64) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDepartmentRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDepartmentRepository)(nil).GetByID), ctx, id)
}

// GetChildren mocks base method.
func (m *MockDepartmentRepository) GetChildren(ctx context.Context, parentID int64) ([]models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildren", ctx, parentID)
	ret0, _ := ret[0].([]models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChildren indicates an expected call of GetChildren.
func (mr *MockDepartmentRepositoryMockRecorder) GetChildren(ctx, parentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildren", reflect.TypeOf((*MockDepartmentRepository)(nil).GetChildren), ctx, parentID)
}

// GetEmployees mocks base method.
func (m *MockDepartmentRepository) GetEmployees(ctx context.Context, departmentID int64) ([]models.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployees", ctx, departmentID)
	ret0, _ := ret[0].([]models.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployees indicates an expected call of GetEmployees.
func (mr *MockDepartmentRepositoryMockRecorder) GetEmployees(ctx, departmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployees", reflect.TypeOf((*MockDepartmentRepository)(nil).GetEmployees), ctx, departmentID)
}

// ReassignEmployees mocks base method.
func (m *MockDepartmentRepository) ReassignEmployees(ctx context.Context, fromDepartmentID, toDepartmentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignEmployees", ctx, fromDepartmentID, toDepartmentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReassignEmployees indicates an expected call of ReassignEmployees.
func (mr *MockDepartmentRepositoryMockRecorder) ReassignEmployees(ctx, fromDepartmentID, toDepartmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignEmployees", reflect.TypeOf((*MockDepartmentRepository)(nil).ReassignEmployees), ctx, fromDepartmentID, toDepartmentID)
}

// Update mocks base method.
func (m *MockDepartmentRepository) Update(ctx context.Context, department *models.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, department)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDepartmentRepositoryMockRecorder) Update(ctx, department interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDepartmentRepository)(nil).Update), ctx, department)
}
